### ISSUE TITLE
Installing PyWavelets in 3.7b5 causes error

### ISSUE THREAD

**Issue by LiraNuna** [PyWavelets/pywt#375]
Installing PyWavelets 0.5.2 on a clean virtual environment causes an error:

```
Collecting PyWavelets
  Using cached https://files.pythonhosted.org/packages/4b/df/3fff2a8b96ef7df6e4e8642fb7569c3717ae562dd76afe0f96525c0af784/PyWavelets-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3ow3nsna/PyWavelets/setup.py", line 12, in <module>
        from numpy import get_include as get_numpy_include
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-3ow3nsna/PyWavelets/
```

**Comment by phwh** [comment]
I think you can solve this by installing `numpy` manually: `pip install numpy`
Not sure about why it isn't installed automatically though.

**Comment by phwh** [comment]
But there is another issue when trying to install `PyWavelets` in Python 3.7.0 (not the beta). Python 3.7.0 was released on 2018-06-27.

When I try to install PyWavelets with `pip install PyWavelets` it fails and outputs a pretty long compiling log from which I paste only the last 100 lines that contain the errors. Hopefully that makes sense.

If I'm doing something wrong, please let me know.

```
pywt/_extensions/_pywt.c:35012:21: error: no member named 'exc_type' in 'struct _ts'
    *type = tstate->exc_type;
            ~~~~~~  ^
pywt/_extensions/_pywt.c:35013:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    *value = tstate->exc_value;
                     ^~~~~~~~~
                     curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
pywt/_extensions/_pywt.c:35014:19: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
    *tb = tstate->exc_traceback;
                  ^~~~~~~~~~~~~
                  curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
pywt/_extensions/_pywt.c:35021:24: error: no member named 'exc_type' in 'struct _ts'
    tmp_type = tstate->exc_type;
               ~~~~~~  ^
pywt/_extensions/_pywt.c:35022:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tmp_value = tstate->exc_value;
                        ^~~~~~~~~
                        curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
pywt/_extensions/_pywt.c:35023:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
    tmp_tb = tstate->exc_traceback;
                     ^~~~~~~~~~~~~
                     curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
pywt/_extensions/_pywt.c:35024:13: error: no member named 'exc_type' in 'struct _ts'
    tstate->exc_type = type;
    ~~~~~~  ^
pywt/_extensions/_pywt.c:35025:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tstate->exc_value = value;
            ^~~~~~~~~
            curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
pywt/_extensions/_pywt.c:35026:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
    tstate->exc_traceback = tb;
            ^~~~~~~~~~~~~
            curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
pywt/_extensions/_pywt.c:35081:24: error: no member named 'exc_type' in 'struct _ts'
    tmp_type = tstate->exc_type;
               ~~~~~~  ^
pywt/_extensions/_pywt.c:35082:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tmp_value = tstate->exc_value;
                        ^~~~~~~~~
                        curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
pywt/_extensions/_pywt.c:35083:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
    tmp_tb = tstate->exc_traceback;
                     ^~~~~~~~~~~~~
                     curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
pywt/_extensions/_pywt.c:35084:13: error: no member named 'exc_type' in 'struct _ts'
    tstate->exc_type = local_type;
    ~~~~~~  ^
pywt/_extensions/_pywt.c:35085:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tstate->exc_value = local_value;
            ^~~~~~~~~
            curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
pywt/_extensions/_pywt.c:35086:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
    tstate->exc_traceback = local_tb;
            ^~~~~~~~~~~~~
            curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
pywt/_extensions/_pywt.c:36973:24: error: no member named 'exc_type' in 'struct _ts'
    tmp_type = tstate->exc_type;
               ~~~~~~  ^
pywt/_extensions/_pywt.c:36974:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?
    tmp_value = tstate->exc_value;
                        ^~~~~~~~~
                        curexc_value
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
pywt/_extensions/_pywt.c:36975:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
    tmp_tb = tstate->exc_traceback;
                     ^~~~~~~~~~~~~
                     curexc_traceback
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
pywt/_extensions/_pywt.c:36976:13: error: no member named 'exc_type' in 'struct _ts'
    tstate->exc_type = *type;
    ~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
error: command 'clang' failed with exit status 1
```

**Comment by grlee77** [comment]
@phwh 
I think your issue is related to NumPy/Cython rather than PyWavelets itself.  The errors look like the ones reported in these issues:
numpy/numpy#11483
numpy/numpy#10500

If I use Python 3.7 and numpy 1.14.5 from the default Anaconda channel I can build PyWavelets and all tests pass.  Anaconda did not have a Cython package for python 3.7 yet so I had to `pip install cython`.

I will try to add testing on 3.7 to the CI services in the near future.  I am hoping to make a new release in the next few weeks and can add wheels for 3.7 at that time.

For the issue reported by @LiraNuna, we will be adding a `pyproject.toml` file that will let pip know to first install numpy and cython prior to trying to build PyWavelets.

**Comment by phwh** [comment]
Thanks for the clarification! @grlee77

**Comment by phwh** [comment]
After reading through the numpy issues I got it running now:
Installing Cython (`pip install Cython`) in my virtualenv before running `pip install pywavelets` does the trick.

Just in case someone else has the same problem.

**Comment by rgommers** [comment]
`requirements.txt` files are meant for development and don't really belong in a package that's put on PyPI. Certainly it's optional and not a bug.

**Comment by afranchuk** [comment]
Really? I thought they were the only way for pip to construct dependency trees upon install...

**Comment by rgommers** [comment]
No, `pip` will get the `install_requires` and `build_requires` entries from `setup.py`. Read the top of https://pip.readthedocs.io/en/1.1/requirements.html - that's aimed at users not people building packages.

**Comment by afranchuk** [comment]
Maybe an appropriate `setup_requires` entry should be in `setup.cfg` or `setup.py`? For the latter case though, I don't see a way to call setup() without importing numpy for the extension (although clearly I'm not that familiar with setuptools so maybe there is a way to accomplish this?).

**Comment by rgommers** [comment]
Yes you are right - I forgot about that problem. The right fix here will be to add a `setup_requires` entry, and delay the `from numpy import get_include as get_numpy_include` import until after the point where `pip` can query for the `install/setup_requires` metadata. This can be done. 

I'll open a separate issue for this, because the current one is also about a 3.7 specific thing.

**Comment by rgommers** [comment]
done in gh-397

**Comment by rgommers** [comment]
@afranchuk @LiraNuna if you could test gh-399, that would be great.
