### ISSUE TITLE
Unable to activated dump via ADB

### ISSUE THREAD

**Issue by Eklavya0811** [PyWavelets/pywt#730]
Whenever I am trying to use the ADB command to enable dump permissions. I am getting this error 
```Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2384)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2412)
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermissionInternal(PermissionManagerServiceImpl.java:1382)
        at com.android.server.pm.permission.PermissionManagerServiceImpl.grantRuntimePermission(PermissionManagerServiceImpl.java:1364)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:557)
        at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:609)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2717)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:301)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6823)
        at android.os.Binder.shellCommand(Binder.java:1092)
        at android.os.Binder.onTransact(Binder.java:912)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4352)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6807)
        at android.os.Binder.execTransactInternal(Binder.java:1392)
        at android.os.Binder.execTransact(Binder.java:1299)```

**Comment by agriyakhetarpal** [comment]
Hi, @Eklavya0811! This does not look like anything related to PyWavelets or the Python programming language. Are you sure you're filing this issue in the right place?
